### ISSUE TITLE
node version 0.5.6-pre

### ISSUE THREAD

**Issue by dclarke** [mozilla/openwebapps#86]
Basically import needs to be search / replaced everywhere in the test framework.

/home/mozilla/openwebapps/site/tests/serverjs/template.js:8
var import = require('./utils/import').import;
    ^^^^^^

node.js:203
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
SyntaxError: <unknown message reserved_word>
    at Module._compile (module.js:411:25)
    at Object..js (module.js:434:10)
    at Module.load (module.js:335:31)
    at Function._load (module.js:294:12)
    at Module.require (module.js:341:17)
    at require (module.js:352:17)
    at Object.<anonymous> (/home/mozilla/openwebapps/site/tests/run.js:9:12)
    at Module._compile (module.js:416:26)
    at Object..js (module.js:434:10)

**Comment by ianb** [comment]
We should refresh template.js, as I believe it is an external library we brought in.
